version: '3'
services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'backend'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sql7.freemysqlhosting.net/sql7738695
      SPRING_DATASOURCE_USERNAME: sql7738695
      SPRING_DATASOURCE_PASSWORD: 8r2Crcrh9v
    ports:
      - "8083:8083"

  react:
    build:
      context: src/main/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: 'frontend'
    depends_on:
      - rest