logging.level.root: warn

server:
  port: 8083

spring:
  output:
    ansi:
      enabled: always

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    template:
      default-topic: my-topic

  datasource:
    url: jdbc:mysql://localhost:3306/bodb
    username: admin
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update