server:
  port: 8083
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        hbm2ddl:
#          auto: create
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mysql
#    username: root
#    password: ads778899
#  jpa:
#    show-sql: true