server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: ads778899
  jpa:
    show-sql: true

#    server:
#      port: 8083
#    spring:
#      datasource:
#        url: jdbc:mysql://sql.freedb.tech:3306/freedb_bodatabase
#        username: freedb_boadmin
#        password: CSDJU6kcD!5r$ZK
#      jpa:
#        show-sql: true
#        hibernate:
#          ddl-auto: create